version: "3.9"
services:
  web:
    image: node:alpine
    ports:
      - "5173:5173"
    volumes:
      - ".:/app"
    environment:
      NODE_ENV: development
    working_dir: /app
    command: sh -c "cd /app; npm install; npm run dev"